# Generated by Django 5.2.9 on 2025-12-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarorlar', '0002_alter_pqaror_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VQaror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaror_num', models.CharField(unique=True)),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField()),
                ('file', models.FileField(upload_to='VQarorlar/')),
            ],
            options={
                'verbose_name': 'Vazirlik Qarorlari',
            },
        ),
    ]
