# Generated by Django 5.2.9 on 2026-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talabalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('pasport', models.CharField(max_length=9)),
                ('qabul_yili', models.IntegerField(max_length=4)),
                ('faculty', models.CharField(choices=[('Kompyuter injiniring', 'kompyuter injiniring'), ('Axborot texnologiyalar', 'axborot texnologiyalar')])),
                ('group', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('O‘qimoqda', 'o‘qimoqda'), ('Bitirgan', 'bitirgan'), ('To‘xtatgan', 'to‘xtatgan')])),
            ],
        ),
    ]
