# Generated by Django 5.2.9 on 2026-01-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talabalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabalar',
            name='qabul_yili',
            field=models.IntegerField(),
        ),
    ]
