# Generated by Django 5.2.9 on 2026-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talabalar', '0002_alter_talabalar_qabul_yili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabalar',
            name='faculty',
            field=models.CharField(choices=[('Kompyuter', 'kompyuter injiniring'), ('Axborot', 'axborot texnologiyalar')]),
        ),
    ]
