# Generated by Django 5.2.9 on 2026-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talabalar', '0003_alter_talabalar_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabalar',
            name='faculty',
            field=models.CharField(choices=[('Kompyuter', 'Kompyuter injiniring'), ('Axborot', 'Axborot texnologiyalar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='status',
            field=models.CharField(choices=[('O‘qimoqda', 'O‘qimoqda'), ('Bitirgan', 'Bitirgan'), ('To‘xtatgan', 'To‘xtatgan')], max_length=20),
        ),
    ]
